"""2

Revision ID: 0b4a90ff8a13
Revises: a422305af873
Create Date: 2021-06-05 00:25:09.679437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4a90ff8a13'
down_revision = 'a422305af873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_author_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('lang', sa.String(), server_default='ru', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lang')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_author_id_fkey', 'messages', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###
